on: [push]
env:
  MANDY_ENV: "production"
name: LibCoutils CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: "Install build tools."
        run: |
          sudo apt-get update
          sudo apt-get install clang -y
          sudo apt-get install build-essential -y
      - name: "Run tests."
        run: |
          make build_unix
          make setup_test_unix
          make test_unix

      - name: "Run a build."
        run: |
          make build_unix
