on: [push]
name: LibCoutils CI
env:
    NAME: "libcoutils"
    VERSION: "0.1.0"
    
jobs:

  build_and_test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: "Install build tools."
        run: |
          sudo apt-get update
          sudo apt-get install clang -y
          sudo apt-get install build-essential -y

      - name: "Compile the static library."
        run: clang -c src/coutils.c -o coutils.a -Wall -O2 -Xlinker --strip-all

      - name: "Move files."
        run: |
          mv coutils.a tests
          cp -f src/coutils.h tests

      - name: "Run tests."
        run: |
          cd tests
          pwd
          clang tests.c coutils.a coutils.h -O2 -Xlinker --strip-all
          ./a.out
          cd ..
      
      - name: "Post-test info."
        run: |
          file tests/a.out
          du -sh tests/a.out