on: [push]
name: LibCoutils CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: "Install build tools."
        run: |
          sudo apt-get update
          sudo apt-get install clang -y
          sudo apt-get install build-essential -y
      - name: "Compile the shared-object library."
        run: |
          clang --shared src/coutils.c -o coutils.so
          ls

      - name: "Move files."
        run: |
          mv coutils.so tests
          cp -f src/coutils.h tests
          ls

      #- name: "Run tests."
      #  run: |
      #    cd tests
      #    clang tests.c coutils.h coutils.so
      #    mv a.out tests
      #    chmod a+x tests
      #    ./tests
