on: [push]
name: LibCoutils CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: "Install build tools."
        run: |
          sudo apt-get update
          sudo apt-get install clang -y
          sudo apt-get install build-essential -y

      - name: "Compile the static library."
        run: clang -c src/coutils.c -o coutils.a -Wall

      - name: "Move files."
        run: |
          mv coutils.a tests
          cp -f src/coutils.h tests

      - name: "Run tests."
        run: |
          LD_LIBRARY_PATH=.
          cd tests
          pwd
          clang tests.c coutils.a coutils.h
          ./a.out
          cd ..
      
      - name: "Post-test info."
        run: |
          file tests/a.out
          du -sh tests/a.out