on: [push]
name: LibCoutils CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: "Install build tools."
        run: |
          sudo apt-get update
          sudo apt-get install clang -y
          sudo apt-get install build-essential -y

      - name: "Compile the shared-object library."
        run: clang --shared src/coutils.c -o coutils.so -Wall

      - name: "Move files."
        run: |
          mv coutils.so tests
          cp -f src/coutils.h tests

      - name: "Run tests."
        run: |
          LD_LIBRARY_PATH=.
          cd tests
          pwd
          clang tests.c coutils.so coutils.h
          ./a.out